<?php
defined('_JEXEC') or die('Restricted access');
require_once (JPATH_ADMINISTRATOR . '/components/com_j2store/library/appmodel.php');
class J2StoreModelSubscriptions extends J2StoreAppModel
{
   function buildQuery($overrideLimits = false)
   {
       $query = parent::buildQuery($overrideLimits); // TODO: Change the autogenerated stub
       $this->_buildWhereQuery($query);
       return $query;
   }

    protected function _buildWhereQuery(&$query){
        $db = JFactory::getDbo();
        $app = JFactory::getApplication();
        $user = JFactory::getUser();
        $state = $this->getStateFields();

        $query->select($db->qn('#__j2store_orders.user_email'));
        $query->select($db->qn('#__j2store_orders.currency_code'));
        $query->select($db->qn('#__j2store_orders.currency_value'));
        $query->join('LEFT OUTER', '#__j2store_orders ON #__j2store_orders.order_id = #__j2store_subscriptions.order_id');

        $query->select('oi.orderitem_name');
        $query->join('LEFT', '#__j2store_ordersubscriptions as os ON os.orderitem_id = #__j2store_subscriptions.orderitem_id');
        $query->join('LEFT', '#__j2store_orderitems as oi ON oi.j2store_orderitem_id = os.orderitem_id');

        if(isset($state['user_id']) && $state['user_id'] != ''){
            $query->where('#__j2store_subscriptions.user_id = '.$db->q($state['user_id']));
        }

        if(isset($state['search']) && $state['search'] != ''){
            $query->where('#__j2store_orders.user_email LIKE '.$db->q('%'.$state['search'].'%'));
        }

        if($app->isAdmin()){
            $query->select('sc.subscription_count');
            $query->join('LEFT', '(select count(user_id) as subscription_count, user_id  from `#__j2store_subscriptions` Group by user_id) sc ON #__j2store_subscriptions.user_id = sc.user_id');

            if(isset($state['subscription_count']) && $state['subscription_count'] != ''){
                if($state['subscription_count'] > 5){
                    $query->where('sc.subscription_count > '.$db->q(5));
                } else {
                    $query->where('sc.subscription_count <= '.$db->q($state['subscription_count']));
                }

            }
        }

//        $query->select($this->_db->qn('#__j2store_orderitems.orderitem_name'));
//        $query->join('LEFT OUTER', '#__j2store_orderitems ON #__j2store_orderitems.order_id = #__j2store_subscriptions.order_id');
//        if(isset($state['search']) && $state['search'] != ''){
//            $query->where('#__j2store_orders.user_email LIKE '.$db->q('%'.$state['search'].'%').
//                    ' OR #__j2store_orderitems.orderitem_name LIKE '.$db->q('%'.$state['search'].'%'));
//        }
        // do other where query
    }

    function getStateFields(){
        $states = array(
            'search' => $this->getState('search', ''),
            'user_id' => $this->getState('filter_user_id', ''),
            'status' => $this->getState('status', ''),
            'subscription_count' => $this->getState('subscription_count', '')
        );
        return $states;
    }

    /**
     * get j2store Order item based on subscription id
     * */
    public function getOrderItem($sid){
        $db = JFactory::getDbo();
        $query = $db->getQuery(true);
        $query->select('oi.*')->from('#__j2store_subscriptions as s');
        $query->join('LEFT', '#__j2store_ordersubscriptions as os ON os.orderitem_id = s.orderitem_id');
        $query->join('LEFT', '#__j2store_orderitems as oi ON oi.j2store_orderitem_id = os.orderitem_id');
        $query->where('s.j2store_subscription_id = '.$db->q($sid));
        $db->setQuery($query);
        return $db->loadObject();
    }

    /**
     * Get upcoming 7 days renewals
     * */
    public function getUpComingRenewals($type = 'upcoming'){
        $state = $this->getStateFields();
        $db = JFactory::getDbo();
        $query = $db->getQuery(true);
        $query->select('s.*')->from('#__j2store_subscriptions as s');

        $query->select($db->qn('#__j2store_orders.user_email'));
        $query->select($db->qn('#__j2store_orders.currency_code'));
        $query->select($db->qn('#__j2store_orders.currency_value'));
        $query->join('LEFT OUTER', '#__j2store_orders ON #__j2store_orders.order_id = s.order_id');

        $query->select('oi.orderitem_name');
        $query->join('LEFT', '#__j2store_ordersubscriptions as os ON os.orderitem_id = s.orderitem_id');
        $query->join('LEFT', '#__j2store_orderitems as oi ON oi.j2store_orderitem_id = os.orderitem_id');

        if(isset($state['search']) && $state['search'] != ''){
            $query->where('#__j2store_orders.user_email LIKE '.$db->q('%'.$state['search'].'%'));
        }
        $expiryControl = \J2Store\Subscription\Helper\ExpiryControl::getInstance();
        $currentDate = $expiryControl->getCurrentDate();
        $dateOfNext7Days = $expiryControl->addDaysToTheDate(7, $currentDate);
//        $query->where('s.next_payment_on >= '.$db->q($currentDate));
        $query->where('s.next_payment_on <= '.$db->q($dateOfNext7Days));
        $query->where('s.subscription_length <> 1');
        $query->where('s.next_payment_on <> s.end_on');
        $query->where('(s.status = '.$db->q('active').' OR s.status = '.$db->q('in_trial').')');
        $query->order('s.j2store_subscription_id DESC');
        $db->setQuery($query);
        return $db->loadObjectList();
    }

    /**
     * Get last 7 days renewals
     * */
    public function getLast7Renewals(){
        $state = $this->getStateFields();
        $db = JFactory::getDbo();
        $query = $db->getQuery(true);
        $query->select('s.*')->from('#__j2store_orderitems as oi');

        $query->select('o.user_email, o.created_on as renewed_on');
        $query->join('LEFT', '#__j2store_orders as o ON o.order_id = oi.order_id');

        $query->select('oi.orderitem_name');
        $query->join('LEFT', '#__j2store_ordersubscriptions as os ON os.orderitem_id = oi.j2store_orderitem_id');
        $query->join('LEFT', '#__j2store_subscriptions as s ON os.subscription_id = s.j2store_subscription_id');

        if(isset($state['search']) && $state['search'] != ''){
            $query->where('o.user_email LIKE '.$db->q('%'.$state['search'].'%'));
        }
        $expiryControl = \J2Store\Subscription\Helper\ExpiryControl::getInstance();
        $currentDate = $expiryControl->getCurrentDate();
        $dateOfLast7Days = $expiryControl->subtractDaysToTheDate(70, $currentDate);
        $query->where('o.created_on <= '.$db->q($currentDate));
        $query->where('o.created_on >= '.$db->q($dateOfLast7Days));
        $query->where('oi.orderitem_type = '.$db->q('subscription_renewal'));
        $query->order('s.j2store_subscription_id DESC');
        $db->setQuery($query);
        return $db->loadObjectList();
    }
}
